export {default as Home} from './Home/home';
export {default as Cases} from './Cases/cases';
export {default as GPU} from './GPU/gpu';
export {default as HDD} from './HDD/hdd';
export {default as Memory} from './Memory/memory';
export {default as MOBO} from './MOBO/mobo';
export {default as Processors} from './Processors/processors';
export {default as PSU} from './PSU/psu';
export {default as Profile} from './Profile/profile';